# Reverse for natural scrolling
# https://github.com/mpv-player/mpv/blob/76a5eba991733f41310912c79c60f6c565a77cc9/etc/input.conf#L38-L44
WHEEL_UP      add volume -2
WHEEL_DOWN    add volume  2
WHEEL_LEFT    seek  10         # seek 10 seconds forward
WHEEL_RIGHT   seek -10         # seek 10 seconds backward
