profile=high-quality
hwdec
# Enable HDR
# Incompatible with icc-profile-auto
target-colorspace-hint

video-sync=display-resample
interpolation

keep-open

screenshot-dir=~~desktop/
screenshot-template='%F %p %n'
