-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- Command + C: copy to system clipboard
-- FIXME: Not working
-- vim.keymap.set("v", "<D-c>", '"+y')
