complete -c viu -x -l help -d "Help"
complete -c viu -s m -l mirror -d "Display a mirror of the original image"
complete -c viu -s n -l name -d "Output the name of the file before displaying"
complete -c viu -s 1 -l once -d "Only loop once through the animation"
complete -c viu -s r -l recursive -d "Recurse down directories if passed one"
complete -c viu -s s -l static -d "Show only first frame of gif"
complete -c viu -s t -l transparent -d "Display transparent image with transparent background"
complete -c viu -s V -l version -d "Prints version information"
complete -c viu -s v -l verbose -d "Output what is going on"
complete -c viu -x -s f -l frame-rate -d "Play gif at the given frame rate"
complete -c viu -x -s h -l height -d "Resize the image to a provided height"
complete -c viu -x -s w -l width -d "Resize the image to a provided width"
